auspic/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from web.views import handler404 as custom_404


urlpatterns = (
        [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("wishlist/", include("order.urls", namespace="order")),
        path("main/", include("main.urls", namespace="main")),
        path("product/", include("products.urls", namespace="product")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("accounts/", include("registration.backends.simple.urls")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
        path(
            "OneSignalSDKWorker.js",
            TemplateView.as_view(
                template_name="OneSignalSDKWorker.js", content_type="text/javascript"
            ),
        ),
       
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
        ]
        
    
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
handler404 = custom_404 

# Customizing the Django Admin
admin.site.site_header = "auspic Administration"
admin.site.site_title = "auspic Admin Portal"
admin.site.index_title = "Welcome to auspic Admin Portal"

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("dashboard/", views.IndexView.as_view(), name="index"),
    path("orders/", views.OrderView.as_view(), name="orders"),
    path(
        "order/<str:order_id>/detail/",
        views.OrderDetailView.as_view(),
        name="order_detail",
    ),
    path("order/update/", views.OrderUpdateView.as_view(), name="order_update"),
    # catgory
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path(
        "category/create/", views.CategoryCreateView.as_view(), name="category_create"
    ),
    path(
        "category/<str:pk>/update/",
        views.CategoryUpdate.as_view(),
        name="category_update",
    ),
    path(
        "category/<str:pk>/delete/",
        views.CategoryDelete.as_view(),
        name="category_delete",
    ),
    # subcatgory
    path("subcategories/", views.SubCategoryListView.as_view(), name="subcategories"),
    path(
        "subcategory/create/",
        views.SubCategoryCreateView.as_view(),
        name="subcategory_create",
    ),
    path(
        "subcategory/<str:pk>/update/",
        views.SubCategoryUpdate.as_view(),
        name="subcategory_update",
    ),
    path(
        "subcategory/<str:pk>/delete/",
        views.SubCategoryDelete.as_view(),
        name="subcategory_delete",
    ),
    # tag
    path("tags/", views.TagListView.as_view(), name="tags"),
    path("tag/create/", views.TagCreateView.as_view(), name="tag_create"),
    path("tag/<str:pk>/update/", views.TagUpdateView.as_view(), name="tag_update"),
    path("tag/<str:pk>/delete/", views.TagDeleteView.as_view(), name="tag_delete"),
    # brand
    path("brands/", views.BrandListView.as_view(), name="brands"),
    path("brand/create/", views.BrandCreateView.as_view(), name="brand_create"),
    path(
        "brand/<str:pk>/update/", views.BrandUpdateView.as_view(), name="brand_update"
    ),
    path(
        "brand/<str:pk>/delete/", views.BrandDeleteView.as_view(), name="brand_delete"
    ),
    # fearture
    path("features/", views.FeatureListView.as_view(), name="features"),
    path("feature/create/", views.FeatureCreateView.as_view(), name="feature_create"),
    path(
        "feature/<str:pk>/update/",
        views.FeatureUpdateView.as_view(),
        name="feature_update",
    ),
    path(
        "feature/<str:pk>/delete/",
        views.FeatureDeleteView.as_view(),
        name="feature_delete",
    ),
    # product
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("product/create/", views.CreateProductView.as_view(), name="product_create"),
    path("product/<pk>/edit/", views.ProductUpdate.as_view(), name="product_update"),
    path(
        "product/<str:pk>/delete/", views.ProductDelete.as_view(), name="product_delete"
    ),
    # variant
    path("variants/", views.VariantListView.as_view(), name="variants"),
    path("variant/create/", views.VariantCreateView.as_view(), name="variant_create"),
    path(
         "variant/<str:pk>/update/",
          views.VariantUpdateView.as_view(),
         name="variant_update",
    ),
    path(
        "variant/<str:pk>/delete/",
        views.VarianteDeleteView.as_view(),
        name="variant_delete",
    ),
    # reviews
    path("reviews/", views.ReviewListView.as_view(), name="review_list"),
    path("review/create/", views.ReviewCreateView.as_view(), name="review_create"),
    path("review/<pk>/edit/", views.ReviewUpdateView.as_view(), name="review_update"),
    path(
        "review/<str:pk>/delete/",
        views.ReviewDeleteView.as_view(),
        name="review_delete",
    ),
    # Purchase
    path("purchases/", views.PurchaseListView.as_view(), name="purchase_list"),
    path(
        "purchase/create/", views.PurchaseCreateView.as_view(), name="purchase_create"
    ),
    path(
        "purchase/<str:pk>/update/",
        views.PurchaseUpdateView.as_view(),
        name="purchase_update",
    ),
    path(
        "purchase/<str:pk>/delete/",
        views.PurchaseDeleteView.as_view(),
        name="purchase_delete",
    ),
    # state
    path("states/", views.StateListView.as_view(), name="states"),
    path("state/create/", views.StateCreateView.as_view(), name="state_create"),
    path(
        "state/<str:pk>/update/", views.StateUpdateView.as_view(), name="state_update"
    ),
    path(
        "state/<str:pk>/delete/", views.StateDeleteView.as_view(), name="state_delete"
    ),
    # district
    path("districts/", views.DistrictListView.as_view(), name="districts"),
    path(
        "district/create/", views.DistrictCreateView.as_view(), name="district_create"
    ),
    path(
        "district/<str:pk>/update/",
        views.DistrictUpdateView.as_view(),
        name="district_update",
    ),
    path(
        "district/<str:pk>/delete/",
        views.DistrictDeleteView.as_view(),
        name="district_delete",
    ),
    # Banner
    path("banners/", views.BannerListView.as_view(), name="banners"),
    path("banner/create/", views.BannerCreateView.as_view(), name="banner_create"),
    path(
        "banner/<str:pk>/update/",
        views.BannerUpdateView.as_view(),
        name="banner_update",
    ),
    path(
        "banner/<str:pk>/delete/",
        views.BannerDeleteView.as_view(),
        name="banner_delete",
    ),
    # customer
    path("customers/", views.CustomerListView.as_view(), name="customers"),
    # Category List
    path("categorylist/", views.CategoryListListView.as_view(), name="categorylists"),
    path(
        "categorylist/create/",
        views.CategoryListCreateView.as_view(),
        name="categorylist_create",
    ),
    path(
        "categorylist/<str:pk>/update/",
        views.CategoryListUpdateView.as_view(),
        name="categorylist_update",
    ),
    path(
        "categorylist/<str:pk>/delete/",
        views.CategoryListDeleteView.as_view(),
        name="categorylist_delete",
    ),
    # Gift Card
    path("giftcards/", views.GiftCardListView.as_view(), name="giftcards"),
    path("giftcard/create/", views.GiftCardCreateView.as_view(), name="giftcard_create"),
    path(
        "giftcard/<str:pk>/update/",
        views.GiftCardUpdateView.as_view(),
        name="giftcard_update",
    ),
    path(
        "giftcard/<str:pk>/delete/",
        views.GiftCardDeleteView.as_view(),
        name="giftcard_delete",
    ),

    path("cities/", views.CityListView.as_view(), name="cities"),
    path("city/create/", views.CityCreateView.as_view(), name="city_create"),
    path("city/<int:pk>/update/", views.CityUpdateView.as_view(), name="city_update"),
    path("city/<int:pk>/delete/", views.CityDeleteView.as_view(), name="city_delete"),

    # Pincode URLs
    path("pincodes/", views.PincodeListView.as_view(), name="pincodes"),
    path("pincode/create/", views.PincodeCreateView.as_view(), name="pincode_create"),
    path("pincode/<int:pk>/update/", views.PincodeUpdateView.as_view(), name="pincode_update"),
    path("pincode/<int:pk>/delete/", views.PincodeDeleteView.as_view(), name="pincode_delete"),
]

web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", TemplateView.as_view(template_name="web/about.html"), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    # policy
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="web/privacy_policy.html"),
        name="privacy_policy",
    ),
    path(
        "terms-conditions/",
        TemplateView.as_view(template_name="web/terms_conditions.html"),
        name="terms_conditions",
    ),
    path(
        "refund-policy/",
        TemplateView.as_view(template_name="web/refund_policy.html"),
        name="refund_policy",
    ),
    path(
        "shipping-policy/",
        TemplateView.as_view(template_name="web/shipping_policy.html"),
        name="shipping_policy",
    ),
    path(
        "contact-policy/",
        TemplateView.as_view(template_name="web/contact_policy.html"),
        name="contact_policy",
    ),
    # cart
    path("shop/cart/", views.cart_view, name="cart"),
    path("shop/cart/add/", views.cart_add, name="add_cart"),
    path("shop/cart/plus/", views.cart_plus, name="cart_plus"),
    path(
        "shop/cart-item-clear/<str:item_id>/",
        views.clear_cart_item,
        name="clear_cart_item",
    ),
    path("shop/cart-minus/", views.minus_to_cart, name="minus_to_cart"),
    path("shop/cart-clear/", views.clear_cart, name="clear_cart"),
    # shop
    path("shop/", views.ShopView.as_view(), name="shop"),
    path("shop/<slug:category_slug>/", views.ShopView.as_view(), name="shop_by_category"),

    path(
        "product-detail/<slug:slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
        path("apply-gift-card/", views.apply_gift_card, name="apply_gift_card"),

    # payment
    path("payment/<str:pk>/", views.PaymentView.as_view(), name="payment"),
    path("callback/<str:pk>/", views.callback, name="callback"),
    path(
        "complete-order/<str:pk>/",
        views.CompleteOrderView.as_view(),
        name="complete_order",
    ),
    path("tracking/", views.tracking, name="tracking"),
    path("tracking/<str:tracking_id>/", views.tracking, name="tracking_view"),
    path('remove_cart',views.cart_remove,name='remove_cart'),
    path("check-pincode/", views.check_pincode_ajax, name="check_pincode_ajax"),

        path(
        "test/",
        TemplateView.as_view(template_name="web/test.html"),
        name="test",
    ),
      path("order_list/<str:pk>/", views.OrderSummaryView.as_view(), name="order_list"),

]

main/models.py
from uuid import uuid4

from django.db import models

# CHOICES
GENDER_CHOICES = (("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other"))

COLOR_CHOICES = (
    ("danger", "red"),
    ("success", "Green"),
    ("info", "Blue"),
    ("warning", "Yellow"),
)

UNIT_CHOICES = (
    ("kg", "Kilogram"),
    ("pc", "Piece"),
    ("g", "Gram"),
    ("ltr", "Liter"),
    ("ml", "Milliliter"),
    ("m", "Meter"),
    ("cm", "Centimeter"),
)


# Create your models here.
class BaseModel(models.Model):
    BOOL_CHOICES = ((True, "Yes"), (False, "No"))

    id = models.UUIDField(primary_key=True, default=uuid4, editable=False, blank=True)
    created = models.DateTimeField(db_index=True, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        "accounts.User",
        blank=True,
        null=True,
        related_name="creator_%(class)s_objects",
        on_delete=models.CASCADE,
    )
    is_active = models.BooleanField(
        "Mark as Active", default=True, choices=BOOL_CHOICES
    )

    class Meta:
        abstract = True


class State(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return str(self.name)


class District(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    delivery_charge = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.name)

templates/dashboard/categorylist/entry.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block title %}{{title}}{% endblock%} 
{% block content %}
<div class="row mb-8">
  <div class="col-md-12">
    <div class="d-md-flex justify-content-between align-items-center">
      <div>
        <h2 class="m-0">{{title}}</h2>
      </div>
      <div class="mt-5 mt-md-0">
        <a onclick="history.back()" class="btn btn-light">Back to Category List</a>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12 col-12">
    <div class="card mb-6 card-lg">
      <div class="card-body p-6 ">
        <form method="POST" enctype="multipart/form-data" class="ajax redirect" data-redirect="{% url 'main:giftcards' %}">
          {% csrf_token %}
       
          <div class="mt-2 row">
            <!-- input -->
            <div class="mb-3 col-lg-6">
              <label class="form-label">{{form.title.label}} {% if form.title.field.required %}<span class="text-danger">*</span>{% endif %} </label>
              {{ form.title }}
            </div>
            <div class="mb-3 col-lg-6">
              <label class="form-label">{{form.category.label}} {% if form.category.field.required %}<span class="text-danger">*</span>{% endif %}</label>
              {{form.category}}
            </div>
            
            <div class="col-lg-12">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block js_plugins %}
{% include 'web/includes/form-ajax.html' %}
<script>
  $(document).ready(function () {
    // Function to update the slug based on the name
    function updateSlug() {
        var name = $('#id_name').val();
        var slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
        $('#id_slug').val(slug);
    }

    // Attach the function to the change event of the name field
    $('#id_name').on('input', updateSlug);
});
</script>
{% endblock %}

templates/dashboard/categorylist/list.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block title %}Category Lists{% endblock%} 
{% block content %}
<!-- row -->
<div class="row mb-8">
    <div class="col-md-12">
        <div class="d-md-flex justify-content-between align-items-center">
            <!-- pageheader -->
            <div>
                <h2 class="m-0">Category Lists</h2>
            </div>
            <!-- button -->
            <div class="mt-5 mt-md-0">
                <a href="{% url 'main:categorylist_create' %}" class="btn btn-primary">Add New Category List</a>
            </div>
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-xl-12 col-12 mb-5">
        <!-- card -->
        <div class="card h-100 card-lg">
            <!-- card body -->
            <div class="card-body p-5">
                <!-- table -->
                <div class="table-responsive ">
                    <table id="myTable" class="table table-centered table-hover mb-0 text-nowrap table-borderless">
                        <thead class="bg-light">
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Category</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for category in categorylist_list %}
                            <tr>  
                                <td>{{forloop.counter}}</td>
                                <td><a href="{% url 'main:categorylist_update' category.pk %}" class="text-reset">{{ category.title }}</a></td>              
                              
                                <td>{{ category.category }}</td>
                                <td>
                                    <div class="dropdown">
                                        <a href="#" class="text-reset" data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="feather-icon icon-more-vertical fs-5"></i>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="{% url 'main:categorylist_delete' category.pk %}"><i class="bi bi-trash me-3"></i>Delete</a></li>
                                            <li><a class="dropdown-item" href="{% url 'main:categorylist_update' category.pk %}"><i class="bi bi-pencil-square me-3 "></i>Edit</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="{% static 'app/css/dataTable.css' %}">
{% endblock %}

{% block js %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>

<script>
    let table = new DataTable('#myTable', {
        responsive: true
    });
 
</script>

{% endblock  %}